fix: Open a PR instead of pushing a commit from bump workflow (#4)
Bump workflow tried to push a commit, which cannot be bypassed for
github-actions bot, and so that failed:
https://github.com/archon-research/uikit/actions/runs/24727050875/job/72330832325

```
Error: Command failed with exit code 1: git push --tags https://github.com/archon-research/uikit HEAD:main
remote: error: GH013: Repository rule violations found for refs/heads/main.        
remote: Review all repository rules at https://github.com/archon-research/uikit/rules?ref=refs%2Fheads%2Fmain        
remote: 
remote: - Changes must be made through a pull request.        
remote: 
remote: - Required status check "lint" is expected.        
remote: 
remote: - Commits must have verified signatures.        
remote:   Found 1 violation:        
remote: 
remote:   7538edbefb79fa47cd632ec39c40b000ad2deb07        
remote: 
To https://github.com/archon-research/uikit
 ! [remote rejected] HEAD -> main (push declined due to repository rule violations)
 ```
 
 This changes the flow to open a PR instead.